services:
  tasks_api_db:
    image: bitnami/postgresql
    container_name: tasks_api_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tasksapidb